# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tx_config.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(765, 1206)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 170, 701, 221))
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.SaveandRestart = QtWidgets.QPushButton(self.centralwidget)
        self.SaveandRestart.setGeometry(QtCore.QRect(30, 400, 161, 41))
        self.SaveandRestart.setObjectName("SaveandRestart")
        self.RunManualPhase = QtWidgets.QPushButton(self.centralwidget)
        self.RunManualPhase.setGeometry(QtCore.QRect(240, 840, 211, 41))
        self.RunManualPhase.setObjectName("RunManualPhase")
        self.text_InputPhaseShiftValue = QtWidgets.QTextEdit(self.centralwidget)
        self.text_InputPhaseShiftValue.setGeometry(QtCore.QRect(30, 840, 201, 41))
        self.text_InputPhaseShiftValue.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.text_InputPhaseShiftValue.setObjectName("text_InputPhaseShiftValue")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 510, 711, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 970, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 1050, 131, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 1010, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 970, 171, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 1010, 251, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 1050, 221, 17))
        self.label_6.setObjectName("label_6")
        self.text_InputUrlCusServer = QtWidgets.QTextEdit(self.centralwidget)
        self.text_InputUrlCusServer.setGeometry(QtCore.QRect(350, 1080, 261, 41))
        self.text_InputUrlCusServer.setObjectName("text_InputUrlCusServer")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 1080, 181, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 1140, 181, 17))
        self.label_8.setObjectName("label_8")
        self.Restart_DataChannel = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_DataChannel.setGeometry(QtCore.QRect(240, 960, 89, 31))
        self.Restart_DataChannel.setObjectName("Restart_DataChannel")
        self.Copy_log = QtWidgets.QPushButton(self.centralwidget)
        self.Copy_log.setGeometry(QtCore.QRect(240, 1130, 91, 31))
        self.Copy_log.setObjectName("Copy_log")
        self.Restart_DataLog = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_DataLog.setGeometry(QtCore.QRect(240, 1000, 89, 31))
        self.Restart_DataLog.setObjectName("Restart_DataLog")
        self.Restart_ReadSensorData = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_ReadSensorData.setGeometry(QtCore.QRect(240, 1040, 89, 31))
        self.Restart_ReadSensorData.setObjectName("Restart_ReadSensorData")
        self.Restart_DataOutputModbus = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_DataOutputModbus.setGeometry(QtCore.QRect(240, 1080, 89, 31))
        self.Restart_DataOutputModbus.setObjectName("Restart_DataOutputModbus")
        self.Restart_TimeSharing = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_TimeSharing.setGeometry(QtCore.QRect(640, 950, 89, 31))
        self.Restart_TimeSharing.setObjectName("Restart_TimeSharing")
        self.Restart_wedLocalServer = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_wedLocalServer.setGeometry(QtCore.QRect(640, 1000, 89, 31))
        self.Restart_wedLocalServer.setObjectName("Restart_wedLocalServer")
        self.Restart_CustomServer = QtWidgets.QPushButton(self.centralwidget)
        self.Restart_CustomServer.setGeometry(QtCore.QRect(640, 1050, 89, 31))
        self.Restart_CustomServer.setObjectName("Restart_CustomServer")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 70, 201, 41))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(590, 10, 141, 91))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../../Pictures/Screenshot from 2020-02-06 17-40-16.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 126, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 470, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(30, 920, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 460, 701, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 890, 701, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 765, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TFi Configuration"))
        self.SaveandRestart.setText(_translate("MainWindow", "Save and Restart"))
        self.RunManualPhase.setText(_translate("MainWindow", "Run Manual Phase"))
        self.label.setText(_translate("MainWindow", "Data Channel"))
        self.label_2.setText(_translate("MainWindow", "Read Sensor Data"))
        self.label_3.setText(_translate("MainWindow", "Data Log"))
        self.label_4.setText(_translate("MainWindow", "Time Sharing Sequence"))
        self.label_5.setText(_translate("MainWindow", "Output to Default Web/Local Sever"))
        self.label_6.setText(_translate("MainWindow", "Output to Custom Web Server"))
        self.label_7.setText(_translate("MainWindow", "Output Data to MODBUS"))
        self.label_8.setText(_translate("MainWindow", "Copy Log File to Desktop"))
        self.Restart_DataChannel.setText(_translate("MainWindow", "Restart"))
        self.Copy_log.setText(_translate("MainWindow", "Copy"))
        self.Restart_DataLog.setText(_translate("MainWindow", "Restart"))
        self.Restart_ReadSensorData.setText(_translate("MainWindow", "Restart"))
        self.Restart_DataOutputModbus.setText(_translate("MainWindow", "Restart"))
        self.Restart_TimeSharing.setText(_translate("MainWindow", "Restart"))
        self.Restart_wedLocalServer.setText(_translate("MainWindow", "Restart"))
        self.Restart_CustomServer.setText(_translate("MainWindow", "Restart"))
        self.label_9.setText(_translate("MainWindow", "TransferFi Gateway"))
        self.label_10.setText(_translate("MainWindow", "Diagnostic Dashboard"))
        self.label_12.setText(_translate("MainWindow", "1. Sensor Database"))
        self.label_13.setText(_translate("MainWindow", "2. Manual Phase Shifting"))
        self.label_14.setText(_translate("MainWindow", "3. Boot Up Features"))

